=== Gabriel-CorP/xmlvalido_GRUPO09/ejercicioII2a/ejercicio-ii-2a-dtd.dtd
<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, telefono*, DUI?, NIT?,AFP?,ISSS?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
        <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
		<!ATTLIST telefono tipo (fijo|celular) #IMPLIED>
		<!ELEMENT DUI  (#PCDATA) >
		<!ELEMENT NIT (#PCDATA) >
		<!ELEMENT AFP (#PCDATA)>
		<!ELEMENT ISSS (#PCDATA) >
		<!ELEMENT a (#PCDATA) >
		<!ATTLIST a  
  		href CDATA #IMPLIED
  		xmlns CDATA #IMPLIED 
 		 target (_blank|_self|marco) "_blank">
		]>
<fichero>

=== Gabriel-CorP/xmlvalido_GRUPO09/ejercicioII2a/ejercicio-ii-2a-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ejercicio-ii-1a-dtd.xml  GRUPO 09 -->
<?xml-stylesheet type="text/css" href="../css/ejercicio-ii-2a-dtd.css" ?>

<!DOCTYPE fichero SYSTEM "ejercicio-ii-2a-dtd.dtd">
<fichero>
 <ficha>
 <a xmlns="http://www.w3.org/1999/xhtml" href="../index.html" target="marco">Inicio</a>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <telefono tipo="celular">74897909</telefono>
  <DUI>007805434-8</DUI>
  <NIT>007-13042024-348</NIT>
  <ISSS>007-13042024-348</ISSS>
 </ficha>
</fichero>
