=== Gabriel-CorP/xmlvalido_GRUPO09/ejercicioIII/tareas.dtd
<!-- ficha.dtd -->
<!ELEMENT archivo (documento+)>
<!ELEMENT documento (facultad, carrera,materia,modalidad,año?)>
<!ATTLIST documento universidad  CDATA  #FIXED "Universidad de El Salvador">
<!ELEMENT facultad (#PCDATA)>
<!ATTLIST facultad codigo  CDATA  #REQUIRED>
<!ELEMENT carrera (#PCDATA)>
<!ATTLIST carrera codigo  CDATA  #REQUIRED>
<!ELEMENT materia (equipo)>
<!ATTLIST materia nombre  CDATA  #REQUIRED>
<!ELEMENT modalidad (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT equipo (persona,persona,persona,persona)>
<!ATTLIST equipo numero CDATA #REQUIRED>
<!ATTLIST equipo tema CDATA #REQUIRED>
<!ATTLIST equipo grupo (GT|GL|GD) #REQUIRED>
<!ATTLIST equipo numero de grupo CDATA #REQUIRED>
<!ATTLIST equipo profesor CDATA #REQUIRED>
<!ATTLIST equipo actividad evaluada CDATA #IMPLIED>
<!ATTLIST equipo porcentaje CDATA #IMPLIED>
<!ELEMENT persona (carnet,apellido,nombre)>
<!ATTLIST persona sexo (M|F) #REQUIRED>
<!ELEMENT carnet (#PCDATA)>
<!ATTLIST carnet numero CDATA #REQUIRED>
<!ATTLIST carnet año de vencimiento CDATA #IMPLIED>
<!ELEMENT apellido(#PCDATA)>
<!ELEMENT nombre(#PCDATA)>

=== Gabriel-CorP/xmlvalido_GRUPO09/ejercicioIII/tareas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="../css/tareas.css" ?>
<!DOCTYPE archivo SYSTEM "tareas.dtd">
<archivo>
	<documento>
	  <facultad codigo="FIA">
	  	Facultad de ingenieria y arquitectura
	  </facultad>
	  <carrera codigo="I10515">Ingenieria de sistemas informaticos</carrera>
	  <materia nombre="Tecnicas de programacion para internet">
	  	<equipo numero="09" tema="xml valido" grupo="GT" numerodegrupo="1" profesor="Ing. Balmore Ortiz" actividadevaluada="Guia 32" porcentaje="10%">
	  		<persona sexo="M">
	  			<carnet numero="1" añodevencimiento="2026">AC16082</carnet>
	  			<apellido>Argueta</apellido>
	  			<nombre>Mario</nombre>
	  		</persona>
	  		<persona sexo="M">
	  			<carnet numero="2" añodevencimiento="2026">BH16004</carnet>
	  			<apellido>Barrios</apellido>
	  			<nombre>Brayan</nombre>
	  		</persona>
	  		<persona sexo="F">
	  			<carnet numero="3" añodevencimiento="2026">CH17013</carnet>
	  			<apellido>Castro</apellido>
	  			<nombre>Maira</nombre>
	  		</persona>
	  		<persona sexo="M">
	  			<carnet numero="4" añodevencimiento="2026">CP17005</carnet>
	  			<apellido>Corena</apellido>
	  			<nombre>Gabriel</nombre>
	  		</persona>
	  	</equipo>
	  </materia>
	  <modalidad>Presencial</modalidad>
	  <año>2021</año>
	</documento>
</archivo>
