<?xml version="1.0" encoding="UTF-8"?>
<!-- ejercicio-ii-1a-dtd.xml  GRUPO 09 -->
<?xml-stylesheet type="text/css" href="../css/ejercicio-ii-1a-dtd.css" ?>
<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, telefono*, DUI?, NIT?,AFP?,ISSS?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
        <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT telefono (#PCDATA)>
		<!ATTLIST telefono tipo (fijo|celular) #IMPLIED>
		<!ELEMENT DUI  (#PCDATA) >
		<!ELEMENT NIT (#PCDATA) >
		<!ELEMENT AFP (#PCDATA)>
		<!ELEMENT ISSS (#PCDATA) >
		]>
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <telefono tipo="celular">74897909</telefono>
  <DUI>007805434-8</DUI>
  <NIT>007-13042024-348</NIT>
  <ISSS>007-13042024-348</ISSS>
 </ficha>
</fichero>
