=== Gabriel-CorP/xmlvalido_GRUPO09/ejercicioIV/ejercicioiv.dtd
<!ELEMENT fichero (a,ficha+)>
<!ELEMENT a (#PCDATA) >
<!ATTLIST a  
  href CDATA #IMPLIED
  xmlns CDATA #IMPLIED 
  target (_blank|_self|marco) "_blank">
<!ELEMENT ficha (libro)>
<!ELEMENT libro (isbn,autor+, titulo, subtitulo?,fechapublicacion,genero+,editorial)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT autor(nombre,apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT subtitulo (#PCDATA)>
<!ELEMENT fechapublicacion (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT editorial(nombreE, direccion, telefono)>
<!ELEMENT nombreE (#PCDATA)>
<!ELEMENT direccion(#PCDATA)>
<!ELEMENT telefono(#PCDATA)>

=== Gabriel-CorP/xmlvalido_GRUPO09/ejercicioIV/ejercicioiv.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE fichero SYSTEM "ejercicioiv.dtd">
<fichero>
<a xmlns="http://www.w3.org/1999/xhtml" href="../index.html" target="marco">Inicio</a>
 <ficha>
    <libro>
     <isbn>29435</isbn>
     <autor>
      <nombre>al</nombre>
      <apellido>ad</apellido>
     </autor>
     <titulo>name</titulo>
     <subtitulo>subname</subtitulo>
     <fechapublicacion>256567</fechapublicacion>
     <genero>accion</genero>
     <editorial>
      <nombreE>af</nombreE>
      <direccion>sgsh</direccion>
     <telefono>i3t9</telefono> 
     </editorial>
    </libro>
 </ficha>
</fichero>
